name: TeleportPlugin
version: '1.0-SNAPSHOT'
main: me.not_ryuzaki.teleportPlugin.TeleportPlugin
api-version: '1.21'
commands:
  tpa:
  tpahere:
  tpaccept:
  tpdeny:
  tpcancel:
  spawn:
    description: Teleports you to the world spawn